package com.aurora.paperviewerenvironment;

import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.text.method.ScrollingMovementMethod;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import com.aurora.paperviewerprocessor.paper.Paper;

/**
 * A fragment containing the view for an abstract of the paper
 */
public class AbstractFragment extends Fragment{
    private Paper mPaper;
    private TextView mSectionHeader;
    private TextView mAbstract;

    public AbstractFragment() {
        // Empty constructor (generated by Android Studio)
    }

    /**
     * Returns a new instance of this fragment for the given section
     * number.
     */
    public static AbstractFragment newInstance() {
        return new AbstractFragment();
    }

    public void setPaper(Paper paper){
        this.mPaper = paper;
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {

        // Inflate the view for a section
        View abstractView = inflater.inflate(R.layout.fragment_abstract, container, false);

        mSectionHeader = (TextView) abstractView.findViewById(R.id.abstract_header);
        mSectionHeader.setText("Abstract");

        // Set the abstract
        mAbstract = (TextView) abstractView.findViewById(R.id.abstract_content);
        mAbstract.setText(mPaper.getAbstract());
        // Enable vertical scrolling for the abstract
        mAbstract.setMovementMethod(new ScrollingMovementMethod());

        return abstractView;
    }

}

