package com.aurora.paperviewerenvironment;

import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentPagerAdapter;
import android.text.method.ScrollingMovementMethod;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import com.aurora.paperviewerprocessor.paper.Paper;

/**
 * A fragment containing the view for a section of the paper
 */
public class SectionFragment extends Fragment{
    /*
     * The fragment argument representing the section number for this
     * fragment.
     */
    private static final String ARG_SECTION_NUMBER = "section_number";

    private Paper mPaper;
    private TextView mSectionHeader;
    private TextView mSectionContent;

    public SectionFragment() {
        // Empty constructor (generated by Android Studio)
    }

    /**
     * Returns a new instance of this fragment for the given section
     * number.
     */
    public static SectionFragment newInstance(int sectionNumber) {
        SectionFragment fragment = new SectionFragment();
        Bundle args = new Bundle();
        args.putInt(ARG_SECTION_NUMBER, sectionNumber);
        fragment.setArguments(args);
        return fragment;
    }

    public void setPaper(Paper paper){
        this.mPaper = paper;
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        int index = getArguments().getInt(ARG_SECTION_NUMBER);

        // Inflate the view for a section
        View sectionView = inflater.inflate(R.layout.fragment_section, container, false);

        // Set the section title of the section
        mSectionHeader = (TextView) sectionView.findViewById(R.id.section_header);
        mSectionHeader.setText(mPaper.getSections().get(index).getHeader());

        // Set the section content of the section
        mSectionContent = (TextView) sectionView.findViewById(R.id.section_content);
        mSectionContent.setText(mPaper.getSections().get(index).getContent());
        // Enable vertical scrolling for the section content
        mSectionContent.setMovementMethod(new ScrollingMovementMethod());

        return sectionView;
    }


    /**
     * A {@link FragmentPagerAdapter} that returns a fragment corresponding to
     * one of the sections.
     */
    public class SectionPagerAdapter extends FragmentPagerAdapter {

        public SectionPagerAdapter(FragmentManager fm) {
            super(fm);
        }

        @Override
        public Fragment getItem(int position) {
            // getItem is called to instantiate the fragment for the given page.
            // Return a PlaceholderFragment (defined as a static inner class below).
            return SectionFragment.newInstance(position);
        }

        @Override
        public int getCount() {
            return mPaper.getSections().size();
        }

    }
}

